version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./credentials:/app/credentials
      - ./logs:/app/logs
    env_file:
      - .env
    restart: always
    # Команда для запуска с явным указанием хоста 0.0.0.0
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
